ebpf: Add rust-analyzer settings for neovim lsp
aya-rs/aya-template pull request #117
Opened 2024-10-03 08:38 UTC by cppcoffee

2024-10-03 08:51 UTC, cppcoffee commented
Maybe also remove `.dir-locals.el`

2024-10-03 18:48 UTC, tamird requested changes

2024-10-03 18:48 UTC, tamird commented on .cargo/rust-analyzer.toml
> +linkedProjects = ["Cargo.toml", "lj-lua-bt-ebpf/Cargo.toml"]
> `lj-lua-bt-ebpf/Cargo.toml`

What's this? Why did it replace `{{project-name}}-ebpf/Cargo.toml`?

2024-10-04 01:28 UTC, cppcoffee commented on .cargo/rust-analyzer.toml
> +linkedProjects = ["Cargo.toml", "lj-lua-bt-ebpf/Cargo.toml"]
oh, is's my mistake, use `{{project-name}}-ebpf/Cargo.toml`

2024-10-04 10:02 UTC, tamird approved these changes

2024-10-04 10:02 UTC, merged