Always build eBPF; remove xtask
aya-rs/aya-template pull request #132
Opened 2024-10-30 10:20 UTC by tamird

2024-10-30 10:31 UTC, vadorovsky requested changes

2024-10-30 10:31 UTC, vadorovsky commented on {{project-name}}-ebpf/build.rs
>  use std::env;
```suggestion
```

That should fix the CI failures

2024-10-30 10:33 UTC, tamird commented on {{project-name}}-ebpf/build.rs
>  use std::env;
Yes, done.

2024-10-30 10:45 UTC, vadorovsky requested changes
I think you can fix the current failure by putting

```toml
components = ["rust-src"]
```

into `{{project-name}}-ebpf/rust-toolchain.toml`

2024-10-30 10:51 UTC, vadorovsky commented
> I think you can fix the current failure by putting
> 
> ```toml
> components = ["rust-src"]
> ```
> 
> into `{{project-name}}-ebpf/rust-toolchain.toml`

nvm, we are installing rust-src in the Github workflow yaml, so that's not the issue. Something more fishy is going in with clippy.

I still think that putting it into `rust-toolchain.toml` would be good, so people don't have to install `rust-src` by hand

2024-10-30 15:22 UTC, tamird commented
> > I think you can fix the current failure by putting
> > ```toml
> > components = ["rust-src"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > into `{{project-name}}-ebpf/rust-toolchain.toml`
> 
> nvm, we are installing rust-src in the Github workflow yaml, so that's not the issue. Something more fishy is going in with clippy.

As always, cargo-in-cargo issue. Should be fixed now.

> I still think that putting it into `rust-toolchain.toml` would be good, so people don't have to install `rust-src` by hand

Done.

2024-10-30 15:29 UTC, alessandrod commented on README.md
> +cargo run --release --config 'target."cfg(all())".runner="sudo -E"'
why don't we set this in config.toml? It's what I do for my projects

2024-10-30 15:29 UTC, alessandrod commented on {{project-name}}/build.rs
> +            if key.as_bytes().starts_with(b"RUST") || key.as_bytes().starts_with(b"CARGO") {
isn't this confusing if one intentionally sets RUSTFLAGS?

2024-10-30 16:14 UTC, tamird commented on {{project-name}}/build.rs
> +            if key.as_bytes().starts_with(b"RUST") || key.as_bytes().starts_with(b"CARGO") {
Are you setting RUSTFLAGS for the cargo-in-cargo? What for?

2024-10-30 16:14 UTC, tamird commented on README.md
> +cargo run --release --config 'target."cfg(all())".runner="sudo -E"'
I don't like that as a default. It should be opt in to invoke sudo.

2024-10-30 20:06 UTC, vadorovsky commented on {{project-name}}/build.rs
> +            if key.as_bytes().starts_with(b"RUST") || key.as_bytes().starts_with(b"CARGO") {
I'm on @tamird's side here for one another reason - if someone sets `RUSTFLAGS=-C linker=clang -C link-arg=-fuse-ld=[lld/mold]`, we don't want to pass that to the eBPF crate.

2024-10-30 20:14 UTC, vadorovsky commented on README.md
> +cargo run --release --config 'target."cfg(all())".runner="sudo -E"'
From one hand I find this command quite annoying - the syntax looks really weird.

From the other hand, I do agree that calling `sudo` should be opt in. Maybe someone wants to use `doas` or something else.

Only if cargo supported something env var like `CARGO_RUNNER`, so users could just do `export CARGO_RUNNER="sudo -E"`, which looks less wild.

At the end I think I have a slight preference towards not defaulting, but not gonna insist on it.

2024-10-30 21:23 UTC, vadorovsky approved these changes

2024-10-31 12:49 UTC, alessandrod commented on {{project-name}}/build.rs
> +            if key.as_bytes().starts_with(b"RUST") || key.as_bytes().starts_with(b"CARGO") {
>  Are you setting RUSTFLAGS for the cargo-in-cargo? What for?

I'm doing `RUSTFLAGS=... cargo ...` because it's common and well documented, and people do it all the time. I'm _not_ doing it for cargo-in-cargo, but I don't even know that _you_ are doing cargo-in-cargo?

I don't know what the solution is, but I doubt that silently discarding it is the solution. Maybe we should warn?

2024-10-31 12:51 UTC, tamird commented on {{project-name}}/build.rs
> +            if key.as_bytes().starts_with(b"RUST") || key.as_bytes().starts_with(b"CARGO") {
In other words, there is nothing here that discards your RUSTFLAGS from the top level crate that you are compiling.

2024-10-31 14:28 UTC, tamird commented on {{project-name}}/build.rs
> +            if key.as_bytes().starts_with(b"RUST") || key.as_bytes().starts_with(b"CARGO") {
Fixed. The culprit was RUSTC_WORKSPACE_WRAPPER.

2024-10-31 14:54 UTC, tamird commented on README.md
> +cargo run --release --config 'target."cfg(all())".runner="sudo -E"'
If there are still concerns with this I'll address them in a follow-up.

2024-10-31 14:54 UTC, merged