Add template for socket_filter program type
aya-rs/aya-template pull request #33
Opened 2022-02-09 14:14 UTC by nak3

This patch adds template for socket_filter.
e.g.

```sh
cargo generate --path ~/dev/aya-template \
         --name my-test \
	 -d program_type=socket_filter
```

(The template works with this bug fix for aya https://github.com/aya-rs/aya/pull/228.)

2022-02-09 14:56 UTC, dave-tucker requested changes

2022-02-09 14:56 UTC, dave-tucker commented on cargo-generate.toml
> +    "sock_filter",
This should be `socket_filter`

2022-02-10 02:24 UTC, nak3 commented on cargo-generate.toml
> +    "sock_filter",
Thank you! Fixed.

2022-05-04 18:12 UTC, dave-tucker approved these changes
LGTM

2022-05-04 18:12 UTC, merged