Don't fail on `BpfLogger::init()` error
aya-rs/aya-template pull request #61
Opened 2022-09-20 09:25 UTC by vadorovsky

An error during `BpfLogger` initialization most likely means that `ayalog-ebpf` is not used in the eBPF crate.

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

2022-09-20 11:46 UTC, dave-tucker requested changes

2022-09-20 11:46 UTC, dave-tucker commented on {{project-name}}/src/main.rs
> +        debug!("failed to initialize eBPF logger: {}", e);
Maybe `warn!` might make more sense here...
It would be awesome if a specific error type we can match on for the case of "aya log userspace is enabled but aya-log-ebpf is not being used"

2022-09-20 16:19 UTC, vadorovsky commented on {{project-name}}/src/main.rs
> +        debug!("failed to initialize eBPF logger: {}", e);
Changed to warn, kept the same error message (according to our Discord conversation)

2022-09-21 09:15 UTC, alessandrod approved these changes
Thanks! See comment, then ready to go

2022-09-21 09:15 UTC, alessandrod commented on {{project-name}}/src/main.rs
> +        warn!("failed to initialize eBPF logger: {}", e);
I would add a comment that explains what to do about this warning:

```
// This can happen if you remove all log statements from your eBPF program
warn!(...)
```

2022-09-21 10:20 UTC, merged