Remove unix-specific executor in xtask
aya-rs/aya-template pull request #77
Opened 2023-01-26 11:01 UTC by dmitris

Change unix-specific executor to generic one
to enable xtask working on Windows and eventually
be able to cross-compile on Windows.

Fixes #76.

2023-01-26 11:04 UTC, vadorovsky requested changes

2023-01-26 11:04 UTC, vadorovsky commented on xtask/src/run.rs
> +    assert!(status.success());
I think we should still fail with a descriptive message, not just with an assertion. So something like:

```suggestion
    if !status.success() {
        anyhow::bail!("Failed to run `{}`", args.join(" "));
    }
```

2023-01-26 11:09 UTC, dmitris commented on xtask/src/run.rs
> +    assert!(status.success());
then we probably should do the same with `build_ebpf.rs` as well = show the cargo command with arguments when it fails?

2023-01-27 08:09 UTC, vadorovsky approved these changes

2023-01-27 08:09 UTC, merged