add memlock remove.
aya-rs/aya-template pull request #94
Opened 2023-06-25 13:50 UTC by liyan-ah

To solve issue mentioned in https://github.com/aya-rs/aya/issues/609, add `memlock remove` handle.

2023-06-26 03:30 UTC, liyan-ah commented
@tamird 

Anyone could check this pr?

2023-06-26 03:55 UTC, alessandrod requested changes
Hi, thanks for the PR!

2023-06-26 03:55 UTC, alessandrod commented on {{project-name}}/Cargo.toml
> +rlimit = "0.9.1"
I think we should use the libc crate directly and not depend on another crate to do this

2023-06-26 07:10 UTC, liyan-ah reviewed
use libc instead of rlimit to remove mem-lock.

2023-06-26 07:13 UTC, liyan-ah reviewed
remove whitespace.

2023-06-26 07:14 UTC, liyan-ah commented on {{project-name}}/Cargo.toml
> +rlimit = "0.9.1"
> I think we should use the libc crate directly and not depend on another crate to do this

Use libc instead of rlimit to remove mem-lock.

2023-06-26 07:14 UTC, liyan-ah commented on {{project-name}}/Cargo.toml
> +rlimit = "0.9.1"
@alessandrod

2023-06-26 17:09 UTC, tamird commented on {{project-name}}/src/main.rs
> +        warn!("cannot remove mem lock");
can we make this message a little more informative? it isn't removing "mem lock"; it is removing the limit on locked memory. please include the value of `ret` as well.

2023-06-26 17:09 UTC, tamird commented on {{project-name}}/Cargo.toml
> +libc = "0.2"
can you keep this list alphabetical?

2023-06-26 17:09 UTC, tamird commented on {{project-name}}/src/main.rs
> +    let rlim = libc::rlimit{
can you add a comment here? it's not clear what's being done here and why.

EDIT: that might not be necessary if you improve the warning below.

2023-06-26 17:09 UTC, tamird commented on {{project-name}}/src/main.rs
> +    if !ret == 0{
missing space after `0`. is it possible to run rustfmt on this file?

2023-06-27 06:55 UTC, liyan-ah reviewed
make warn info more informative.

2023-06-27 06:56 UTC, liyan-ah commented
> make warn info more informative.

@tamird @alessandrod

2023-06-30 12:26 UTC, liyan-ah commented
> > make warn info more informative.
> 
> @tamird @alessandrod

@vadorovsky

2023-07-04 07:03 UTC, liyan-ah commented
@alessandrod @tamird @dmitris @lucab 
Anyone could check this pr?

2023-07-04 07:22 UTC, alessandrod requested changes

2023-07-04 07:22 UTC, alessandrod commented on {{project-name}}/src/main.rs
> +    // Allow current process to lock memory for eBPF resources.
```suggestion
    // Bump the memlock rlimit. This is needed for older kernels that don't use the
    // new memcg based accounting, see https://lwn.net/Articles/837122/
```

2023-07-04 07:22 UTC, alessandrod commented on {{project-name}}/src/main.rs
> +        warn!("remove limit on locked memory failed, ret is: {}", ret);
I'd make this debug! and not warn!. For new kernels it isn't needed at all, so it'd just confuse people

2023-07-04 07:27 UTC, liyan-ah commented on {{project-name}}/src/main.rs
> +        warn!("remove limit on locked memory failed, ret is: {}", ret);
debug! is okay.

2023-07-04 11:54 UTC, merged

2023-07-04 11:54 UTC, alessandrod commented
Thank you!